// frontend/src/features/app_shell/dominio/Station1Data.js
const objetos = [
  {ico:'ðŸ’§', nombre:'GalÃ³n de agua', color:'var(--rio)', voz:'GotÃ­n', audioSrc: GOTIN_AUDIO_SRC, saludo:'Â¡Blup, blup! Soy GotÃ­n, Â¡y vengo salpicando historias!', pitch:1.7, rate:1.15, relato:'Cuando Blanca y sus vecinas llegaron a este lugar, el agua no salÃ­a de ningÃºn grifo: habÃ­a que subirla desde la parte baja de la montaÃ±a, galÃ³n por galÃ³n, colgada de los hombros. Los caminos eran de tierra y piedra, y cada subida podÃ­a tomar mÃ¡s de una hora. Aun asÃ­, entre risas y pausas para tomar aliento, las mujeres convirtieron esa tarea dura en un momento de encuentro y compaÃ±Ã­a.'},
  {ico:'ðŸª', nombre:'Cometa', color:'var(--sol)', voz:'Brisa', audioSrc: BRISA_AUDIO_SRC, saludo:'Â¡Wiiii! Soy Brisa, y vuelo tan rÃ¡pido que casi ni me escuchas!', pitch:1.95, rate:1.3, relato:'Los fines de semana, cuando el trabajo daba un respiro, las familias subÃ­an hasta el mirador de la Cruz a elevar cometas de papel hechas a mano. El viento del cerro era, como recuerda Martha Vivas, juego y compaÃ±Ã­a: ahÃ­ arriba se olvidaban las subidas cansadas y el cielo se llenaba de colores. TodavÃ­a hoy, algunas niÃ±as sueÃ±an con volver a ese mismo mirador junto a sus propias hijas.'},
  {ico:'ðŸ²', nombre:'Olla', color:'var(--cafe)', voz:'Abuela Olla', audioSrc: OLLA_AUDIO_SRC, saludo:'Ejem, ejem... soy la Abuela Olla, y llevo muchos, muchos aÃ±os borboteando cuentos.', pitch:0.5, rate:0.75, relato:'En los primeros aÃ±os, cuando aÃºn no habÃ­a luz ni acueducto, las ollas comunitarias reunÃ­an a varias familias alrededor de un mismo fuego. Compartir lo poco que habÃ­a era una forma de resistir juntos al esfuerzo de levantar un barrio desde cero. Esa costumbre de cocinar y comer en comunidad quedÃ³ como una de las memorias mÃ¡s cÃ¡lidas del territorio.'},
  {ico:'ðŸŒ±', nombre:'Semilla', color:'var(--verde)', voz:'BrotÃ­n', audioSrc: BROTIN_AUDIO_SRC, saludo:'Â¡Hola, hola, hola! Soy BrotÃ­n, Â¡tan chiquito y tan hablador!', pitch:2.0, rate:1.25, relato:'Hoy, las niÃ±as de La Mariposa sueÃ±an con sembrar Ã¡rboles mÃ¡gicos cerca de la quebrada y del cerro norte: Ã¡rboles que, dicen ellas, podrÃ­an hablar con los animales y dar refugio a las mariposas. Es un sueÃ±o que mira hacia el futuro, pero que nace de la misma tierra que sus abuelas trabajaron con tanto esfuerzo. Cada semilla sembrada es, en el fondo, una forma de cuidar lo que otras generaciones construyeron.'},
  {ico:'ðŸ§¶', nombre:'Hilo de lana', color:'var(--violeta-suave)', voz:'Lanita', audioSrc: LANITA_AUDIO_SRC, saludo:'Shhh... soy Lanita, y te voy a contar mi historia despacito, con mucho cariÃ±o.', pitch:1.5, rate:0.82, relato:'Ana Cortez naciÃ³ en este barrio y encontrÃ³ en la costura y el crochet una manera de estar activa, de sanar y de acompaÃ±ar a su familia. Cada puntada es paciente, como el propio territorio, que se ha ido tejiendo poco a poco con el trabajo de muchas manos. "AquÃ­ me siento activa y es mi manera de aportar y de sanar", cuenta ella con una sonrisa.'}
];
const CONOZCO_HOTSPOTS = [
  {ico:'ðŸ’§', q:'Â¿CÃ³mo conseguÃ­an agua?', a:'No habÃ­a acueducto: las familias cargaban el agua en baldes y galones desde las pilas de la parte baja, subiendo la montaÃ±a varias veces al dÃ­a.'},
  {ico:'ðŸ”¥', q:'Â¿CÃ³mo cocinaban?', a:'Se cocinaba con leÃ±a recogida en los alrededores, y muchas familias compartÃ­an fogones y ollas comunitarias.'},
  {ico:'ðŸ ', q:'Â¿CÃ³mo eran las primeras casas?', a:'Las primeras casas se construyeron con madera y materiales sencillos, levantadas con el esfuerzo de cada familia.'},
  {ico:'ðŸ‘¥', q:'Â¿CÃ³mo se ayudaban entre vecinos?', a:'Los vecinos compartÃ­an mercado, cuidaban a los niÃ±os de otras familias y se turnaban para las tareas mÃ¡s pesadas.'},
  {ico:'ðŸª', q:'Â¿QuÃ© hacÃ­an para divertirse?', a:'Los fines de semana subÃ­an hasta el mirador de la Cruz a elevar cometas y compartir en familia.'}
];
const CONOZCO_NARRATION = 'Cuando lleguÃ©, solo habÃ­a tres casas. No habÃ­a calles, ni acueducto, ni luz. CocinÃ¡bamos con leÃ±a, recogÃ­amos gasolina en bidones, y pasÃ¡bamos el agua con cuerdas y mangueras desde las pilas. El trabajo era duro, pero yo agradecÃ­a tener buenos vecinos, y poco a poco fuimos levantando una casa que se convirtiÃ³ en mi refugio.';
let hotspotsSeen = new Set();
let conozcoUtterance = null;
let conozcoPlaying = false;
let conozcoVolume = 1;
