// frontend/src/features/app_shell/dominio/Station1Data.js
const objetos = [
  {ico:'gota', nombre:'Galón de agua', color:'var(--rio)', voz:'Gotín', audioSrc: GOTIN_AUDIO_SRC, saludo:'¡Blup, blup! Soy Gotín, ¡y vengo salpicando historias!', pitch:1.7, rate:1.15, relato:'Cuando Blanca y sus vecinas llegaron a este lugar, el agua no salía de ningún grifo: había que subirla desde la parte baja de la montaña, galón por galón, colgada de los hombros. Los caminos eran de tierra y piedra, y cada subida podía tomar más de una hora. Aun así, entre risas y pausas para tomar aliento, las mujeres convirtieron esa tarea dura en un momento de encuentro y compañía.'},
  {ico:'cometa', nombre:'Cometa', color:'var(--sol)', voz:'Brisa', audioSrc: BRISA_AUDIO_SRC, saludo:'¡Wiiii! Soy Brisa, y vuelo tan rápido que casi ni me escuchas!', pitch:1.95, rate:1.3, relato:'Los fines de semana, cuando el trabajo daba un respiro, las familias subían hasta el mirador de la Cruz a elevar cometas de papel hechas a mano. El viento del cerro era, como recuerda Martha Vivas, juego y compañía: ahí arriba se olvidaban las subidas cansadas y el cielo se llenaba de colores. Todavía hoy, algunas niñas sueñan con volver a ese mismo mirador junto a sus propias hijas.'},
  {ico:'olla', nombre:'Olla', color:'var(--cafe)', voz:'Abuela Olla', audioSrc: OLLA_AUDIO_SRC, saludo:'Ejem, ejem... soy la Abuela Olla, y llevo muchos, muchos años borboteando cuentos.', pitch:0.5, rate:0.75, relato:'En los primeros años, cuando aún no había luz ni acueducto, las ollas comunitarias reunían a varias familias alrededor de un mismo fuego. Compartir lo poco que había era una forma de resistir juntos al esfuerzo de levantar un barrio desde cero. Esa costumbre de cocinar y comer en comunidad quedó como una de las memorias más cálidas del territorio.'},
  {ico:'brote', nombre:'Semilla', color:'var(--verde)', voz:'Brotín', audioSrc: BROTIN_AUDIO_SRC, saludo:'¡Hola, hola, hola! Soy Brotín, ¡tan chiquito y tan hablador!', pitch:2.0, rate:1.25, relato:'Hoy, las niñas de La Mariposa sueñan con sembrar árboles mágicos cerca de la quebrada y del cerro norte: árboles que, dicen ellas, podrían hablar con los animales y dar refugio a las mariposas. Es un sueño que mira hacia el futuro, pero que nace de la misma tierra que sus abuelas trabajaron con tanto esfuerzo. Cada semilla sembrada es, en el fondo, una forma de cuidar lo que otras generaciones construyeron.'},
  {ico:'ovillo', nombre:'Hilo de lana', color:'var(--violeta-suave)', voz:'Lanita', audioSrc: LANITA_AUDIO_SRC, saludo:'Shhh... soy Lanita, y te voy a contar mi historia despacito, con mucho cariño.', pitch:1.5, rate:0.82, relato:'Ana Cortez nació en este barrio y encontró en la costura y el crochet una manera de estar activa, de sanar y de acompañar a su familia. Cada puntada es paciente, como el propio territorio, que se ha ido tejiendo poco a poco con el trabajo de muchas manos. "Aquí me siento activa y es mi manera de aportar y de sanar", cuenta ella con una sonrisa.'}
];
const CONOZCO_HOTSPOTS = [
  {ico:'gota', q:'¿Cómo conseguían agua?', a:'No había acueducto: las familias cargaban el agua en baldes y galones desde las pilas de la parte baja, subiendo la montaña varias veces al día.'},
  {ico:'fuego', q:'¿Cómo cocinaban?', a:'Se cocinaba con leña recogida en los alrededores, y muchas familias compartían fogones y ollas comunitarias.'},
  {ico:'casa', q:'¿Cómo eran las primeras casas?', a:'Las primeras casas se construyeron con madera y materiales sencillos, levantadas con el esfuerzo de cada familia.'},
  {ico:'vecinos', q:'¿Cómo se ayudaban entre vecinos?', a:'Los vecinos compartían mercado, cuidaban a los niños de otras familias y se turnaban para las tareas más pesadas.'},
  {ico:'cometa', q:'¿Qué hacían para divertirse?', a:'Los fines de semana subían hasta el mirador de la Cruz a elevar cometas y compartir en familia.'}
];
const CONOZCO_NARRATION = 'Cuando llegué, solo había tres casas. No había calles, ni acueducto, ni luz. Cocinábamos con leña, recogíamos gasolina en bidones, y pasábamos el agua con cuerdas y mangueras desde las pilas. El trabajo era duro, pero yo agradecía tener buenos vecinos, y poco a poco fuimos levantando una casa que se convirtió en mi refugio.';
let hotspotsSeen = new Set();
let conozcoUtterance = null;
let conozcoPlaying = false;
let conozcoVolume = 1;
